---
title: "Results"
author: "Isabelle van der Zanden and Gelieke Steeghs"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, echo = FALSE, warning = FALSE)
```

``` {r package}
library(tidyverse)
library(flextable)
library(car)
library(multcomp)
library(emmeans)
library(factoextra) #pca
library(vegan)
library(lme4)
library(glmmTMB) 
library(DHARMa) #check model assumptions
library(ggbeeswarm) #jitter points
library(broom) #tidy output
```

``` {r upload and mutate files}
#Litter mass loss data
lml <- read_csv2("MASTER_LML.csv")

lml$litter_sp <- factor(lml$litter_sp, levels=c("Alder","Hazel","Chestnut"))
lml$mesh_size <- factor(lml$mesh_size, levels=c("Fine","Medium","Coarse"))
lml <- lml %>% dplyr::rename("code" = "vb_code") 

#Litter and soil properties data
mt <- read_csv2("Soilprop_decomp.csv")
cnp <- read_csv("CNP_data.csv")

# join litter mass data with landuse & location data
lml_2 <- lml %>% left_join(dplyr::select(mt, code, landuse, location), by ="code")

litter_cn <- read_csv2("litter_cn.csv")
litter_lignin <- read_csv2("litter_lignin.csv")
litter_lignin <- litter_lignin %>% dplyr::rename("lignin" = "lignin (mg/g)")

mt_1 <- mt %>% left_join(cnp, by="code")

#sum earthworm abundance, biomass and mites
mt_2 <- mt_1 %>% rowwise() %>% dplyr::mutate(abundance_ew_total = sum(dplyr::c_across(contains("Abundance")))*10) %>%
                              dplyr::mutate(biomass_ew_total = sum(dplyr::c_across(contains("Biomass")))*10) #%>%
                              # dplyr::mutate(mites_sum = sum(dplyr::c_across(contains("Mites"))))
mt_2 <- mt_2 %>% dplyr::rename("vb_code" = "code")

# sum bacteria + actinos
mt_3 <- mt_2 %>% rowwise() %>% dplyr::mutate(bact_total = sum(Bacteria_total,Actinobacteria_total))

#location and landuse as factor
mt_3$location <- factor(mt_3$location)
levels(mt_3$location) <- c("L1","L2", "L3", "L4")

mt_3$loc_lu <- paste(mt_3$location, mt_3$landuse, sep="_")

lml_2$location <- factor(lml_2$location)
levels(lml_2$location) <- c("L1","L2", "L3", "L4")

lml_2$loc_lu <- paste(lml_2$location, lml_2$landuse, sep="_")
```

# Results

``` {r table_soil_props}
tab_order <- c('b.d.','moisture_percentage','ph_kcl','som_percentage', 'ec',
               'Total_P_mg_kg', 'Olsen_P_mg_kg','C_total','N_total',
               'bact_total','AMF_NLFA','Fungi_total',              
               'Springtails_nr_kg','Mites_oribatid_kg','Mites_other_kg',
               'abundance_ew_total','biomass_ew_total')

mt_wide <- mt_3 %>% pivot_longer(cols=c(ec:Olsen_P_mg_kg,
                                        Fungi_total, AMF_NLFA,Springtails_nr_kg,
                                        C_total:N_total, abundance_ew_total:bact_total), names_to="measurement")
mt_wide <- mt_wide %>% mutate(category = if_else(measurement=='b.d.'|measurement=='moisture_percentage',
                                                 "Physical",
                                                 if_else(measurement=='ph_kcl'|measurement=='som_percentage'|measurement=='ec'|
                                                measurement=='Total_P_mg_kg'|measurement== 'Olsen_P_mg_kg'|measurement=="C_total"|measurement=="N_total",
                                              "Chemical","Biological")))

tab <- mt_wide %>% group_by(landuse, category, measurement) %>%
  summarise(mean = sprintf("%1.2f", mean(value, na.rm = TRUE)),
            sd = sprintf("(%1.2f)", sd(value, na.rm = TRUE))) %>%
  unite("value",mean, sd, sep=" ") %>%
  arrange(factor(measurement, levels = tab_order)) %>%
  pivot_wider(names_from=landuse, values_from=value)

tab %>% 
  flextable() %>% 
  labelizor(labels = c(category = "Category", measurement = "Measurements", Food_forest = "Food forest", 
                       Total_P_mg_kg = "Total fosfor (mg/kg)", Olsen_P_mg_kg = "Olsen P (mg/kg)", 
                       b.d. = "Bulk density (g/cm3)", ph_kcl = "pH (KCl)", ec="Electrical conductivity (mS/m)",
                       C_total = "Total C (%)", N_total = "Total N (%)",
                       moisture_percentage = "Soil moisture (%)", 
                       som_percentage = "Soil organic matter (%)", 
                       abundance_ew_total = "Earthworms abundance (#/m2)",
                       biomass_ew_total = "Earthworms biomass (g/m2)",
                       Springtails_nr_kg = "Springtails abundance (#/kg)", 
                       Mites_oribatid_kg = "Mites oribatid abundance (#/kg)",
                       Mites_other_kg = "Mites other abundance (#/kg)",
                       bact_total = "Bacterial biomass (µg/g)",
                       Fungi_total = "Non-AMF fungal biomass (µg/g)",
                       AMF_NLFA = "AMF biomass (µg/g)")) %>%
  merge_v(j = ~ category) %>% 
  hline(j = ~ category, part = "all") %>%
  set_table_properties(layout = "autofit") %>%
  set_caption(caption = "Table 1. ANOVA results comparing food forests to grasslands for chemical, physical and biological variables. Table shows mean (standard deviation), F statistic and p-values.", 
                  style = "Table Caption")

```

## Litter characteristics 

``` {r litter cn lignin table}
# Litter CN data statistics
litter_cn %>% 
  group_by(litter_species) %>%
  summarize(
    mean1 = mean(c_proc),
    sd1 = sd(c_proc),
    mean2 = mean(n_proc),
    sd2 = sd(n_proc),
    mean3 = mean(cn_ratio),
    sd3 = sd(cn_ratio),
  )

cn.lm <- lm(cn_ratio ~ litter_species, data=litter_cn)
summary(cn.lm)
cn_anova <- anova(cn.lm)
cn_anova

cld(emmeans(cn.lm,~ litter_species,adjust="tukey"), Letters = c(letters))

# Litter lignin data statistics

litter_lignin %>% 
  group_by(litter_species) %>%
  summarize(
    min = min(lignin),
    max = max(lignin),
    mean = mean(lignin),
    sd = sd(lignin)
  )

lignin.lm <- lm(lignin ~ litter_species, data=litter_lignin)
summary(lignin.lm)
lignin_anova <- anova(lignin.lm)
cld(emmeans(lignin.lm,~ litter_species,adjust="tukey"), Letters = c(letters))

# C
c.lm <- lm(c_proc ~ litter_species, data=litter_cn)
hist(residuals(c.lm))
shapiro.test(residuals(c.lm))
anova(c.lm)
cld(emmeans(c.lm,~ litter_species,adjust="tukey"), Letters = c(letters))

# N
n.lm <- lm(n_proc ~ litter_species, data=litter_cn)
hist(residuals(n.lm))
anova(n.lm)
cld(emmeans(n.lm,~ litter_species,adjust="tukey"), Letters = c(letters))
```

## Litter mass loss data  


```{r three way}
#take NAs out
lml_3 <- filter(lml_2, !is.na(litter_mass_loss_final))
#transform data necessary for different models
# lml_3 <- lml_3 %>% mutate(litter_mass_loss_final = ifelse(litter_mass_loss_final > 1,
#                                                          1, litter_mass_loss_final))
# lml_3$litter_mass_loss_final_no_0_1 <- pmin(pmax(lml_3$litter_mass_loss_final, 
#                                                  0.0001), 0.9999)

#different models
# three_way_gauss <- glmmTMB(litter_mass_loss_final ~ landuse * litter_sp * mesh_size 
#                                + (1|location), family=gaussian(), 
#                            data=lml_3, na.action="na.omit")
three_way_gauss_disp <- glmmTMB(litter_mass_loss_final ~ landuse * litter_sp * 
                                  mesh_size + (1|location), 
                               family=gaussian, dispformula = ~ litter_sp,
                        data=lml_3, na.action="na.omit")

# anova(three_way_gauss_disp, three_way_gauss) #gaussian with dispersion is better
simres <- simulateResiduals(three_way_gauss_disp)
plot(simres) #no severe issues
plotResiduals(simres, lml_3$mesh_size)
emmip(three_way_gauss_disp, landuse ~ litter_sp | mesh_size )
emm <- emmeans(three_way_gauss_disp, ~ landuse * litter_sp * mesh_size, type="response", adjust="Tukey")
# joint_tests(three_way_gauss_disp) %>% flextable()
(contrasts <- contrast(emm, "pairwise", simple="each", combine = TRUE, adjust="Tukey"))
contrasts_df <- as.data.frame(contrasts)
pairs(emmeans(emm, ~ litter_sp, type="response", adjust="Tukey"))
three_way_cld <- cld(emmeans(three_way_gauss_disp, ~ landuse * litter_sp * mesh_size, adjust="Tukey"), Letters = letters)
three_way_cld

#visualize interaction effect
emm_df <- as.data.frame(emm)
ggplot(emm_df, aes(x = landuse, y = emmean, color = litter_sp, group = litter_sp)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ mesh_size) +
  labs(y = "Estimated Mean", x = "landuse", color = "Litter species")

# Plot the outcomes
image <- lml_3 %>%
  ggplot(aes(x=landuse, y=litter_mass_loss_final, fill=landuse, color=landuse)) +
  geom_boxplot(coef=0, outlier.shape = NA, alpha=0.5, show.legend = FALSE, width=0.5) +
  scale_fill_manual(values=c("#56B4E9", "#D55E00" ),
                    labels=c("Food forest","Grassland")) + 
  scale_color_manual(values=c("#56B4E9", "#D55E00" ),
                    labels=c("Food forest","Grassland")) + 
  geom_beeswarm(aes(color = landuse), dodge.width = 1, cex = 2.5) +
  geom_point(
    data = three_way_cld,
    aes(y = emmean, x = landuse),
    size = 2,
    color = "black", show.legend = FALSE
  ) +
    geom_errorbar(
    data = three_way_cld,
    aes(y=emmean, ymin = lower.CL, ymax = upper.CL, x = landuse),
    width = 0,
    linewidth = 0.5, 
    color = "black", show.legend = FALSE
  ) +
  geom_text(data = three_way_cld, aes(x = landuse, y = upper.CL, label = .group), show.legend = FALSE) +
  facet_grid(litter_sp ~ mesh_size) +
  theme_bw(base_size = 20) +
  theme(legend.position="bottom") +
  scale_x_discrete(labels=c("Food forest", "Grassland")) +
  labs(y="Litter mass loss", x="Land use", fill="Landuse")
image
ggsave(file="LML_final.svg", width=12, height=10)
```

# Supplement

## PCA soil properties

``` {r PCA }
#pca with earthworms + micro-arthropods
mt_3_pca <- mt_3 %>% dplyr::select(c(landuse,location,loc_lu,ph_kcl,moisture_percentage,som_percentage,
                                     b.d.,ec,Total_P_mg_kg,Olsen_P_mg_kg,
                                     C_total,N_total,
                                     AMF_NLFA,
                                     Mites_oribatid_kg,Mites_oribatid_kg,Mites_other_kg,
                                     Springtails_nr_kg,abundance_ew_total,biomass_ew_total))

colSums(is.na(mt_3_pca))
mt_3_pca_nomiss <- na.omit(mt_3_pca) # 3 plots per site only for which there is earthworm and arthropod data
colSums(is.na(mt_3_pca_nomiss))

mt_3_pca_done <- mt_3_pca_nomiss %>% dplyr::select(!c(landuse,location,loc_lu))

pca <- prcomp(mt_3_pca_done, scale=TRUE)
# fviz_eig(pca) #check scree plot

fviz_pca_biplot(pca, label="var", palette = "Paired", 
                pointshape=21, fill.ind = mt_3_pca_nomiss$loc_lu, 
                col.ind = "black",
                pointsize=4, mean.point = FALSE, col.var = "#767676",
                legend.title="Locations and land uses", 
                repel=TRUE, title="")+ 
                xlim(-4,4) + ylim(-4,4) +
                theme(legend.position="bottom",
                      text = element_text(size = 14)) +
                guides(fill=guide_legend(title.position="top", 
                                     title.hjust =0.5)) + 
                xlab("PC1 (39.0%)") +
                ylab("PC2 (21.4%)")


ggsave("pca_small.png", width=8, height=8)
ggsave("pca_small_.svg")

``` 


## PERMANOVA output soil properties

``` {r adonis}
char_dist <- vegdist(mt_3_pca_done, method="bray")

char_div <- adonis2(char_dist ~ location*landuse, data=mt_3_pca_nomiss, permutations = 999, method="bray", by="terms")

char_div

char_tab <- tidy(char_div) %>% flextable()
char_tab
```

